# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.caseypore.com
title: Casey Pore's Personal Page
email: caseypore@gmail.com
author: Casey Pore
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2018 Casey Pore. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: resume
    url: https://cpore.github.io/resume.html
  - title: github
    url: https://github.com/cpore
  - title: linkedin
    url: https://www.linkedin.com/in/casey-pore-8487a665/
